# Generated by Django 4.2.21 on 2025-05-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '學生'), ('admin', '管理員')], default='student', max_length=10),
        ),
    ]
