# Generated by Django 4.2.21 on 2025-05-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
