# Generated by Django 4.2.21 on 2025-05-28 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_wrongquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrongquestion',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 28, 9, 24, 39, 185192, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='fixed_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
